# Generated by Django 4.0.3 on 2022-06-11 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_author_log_tag_delete_user_log_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='author_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='log.author'),
        ),
        migrations.AlterField(
            model_name='log',
            name='contents',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='log',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='log.category'),
        ),
    ]
