# Generated by Django 4.0.3 on 2022-06-14 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_category_alter_log_author_name_alter_log_contents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='latest_edit_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
