# Generated by Django 4.0.3 on 2022-06-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_rename_latest_edit_time_log_edit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(default='', max_length=255)),
        ),
    ]
