# Generated by Django 4.0.3 on 2022-06-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_log_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
