# Generated by Django 4.0.3 on 2022-06-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='category',
            new_name='categories',
        ),
    ]
